CREATE OR ALTER EXCEPTION EX_USUARIO_MAIL_EXISTE '';
CREATE OR ALTER EXCEPTION EX_USUARIO_LOGIN_ERROR '';
CREATE OR ALTER EXCEPTION EX_SUPER_ADMIN_ERROR '';
CREATE OR ALTER EXCEPTION EX_USUARIO_MAIL_NO_EXISTE '';
CREATE OR ALTER EXCEPTION EX_ADMINISTRADOR_ERROR '';
CREATE OR ALTER EXCEPTION EX_TRABAJADOR_ERROR '';
CREATE OR ALTER EXCEPTION EX_ROL_ERROR '';



SET TERM ^;

CREATE OR ALTER PROCEDURE PRI_SESION_SUPER_ADMIN(ID_SESION T_ID)
RETURNS(OK T_LOGICO)
AS
DECLARE ID_SUPER_ADMIN T_ID;
BEGIN 
    /*COMPROBAR SI ES SUPER_ADMIN*/
    SELECT A.ID_SUPER_ADMIN 
    FROM SUPER_ADMIN A
    JOIN USUARIO U ON A.ID_USUARIO=U.ID_USUARIO
    JOIN SESION S ON U.ID_USUARIO=S.ID_USUARIO
    WHERE S.ID_SESION=:ID_SESION
    AND U.ACTIVO='S'
    AND S.FECHA_FIN IS NULL
    INTO :ID_SUPER_ADMIN;
    IF (ID_SUPER_ADMIN IS NULL) THEN EXCEPTION EX_SUPER_ADMIN_ERROR;
    /*ACTUALIZAR LA SESION*/
    UPDATE SESION 
    SET FECHA_ACCESO='NOW'
    WHERE ID_SESION=:ID_SESION;
    /*VOLVER*/
    OK='S';
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE PRI_SESION_ADMIN(ID_SESION T_ID,ID_EMPRESA T_ID)
RETURNS(OK T_LOGICO)
AS
DECLARE ID_ADMINISTRADOR T_ID;
BEGIN 
    SELECT A.ID_ADMINISTRADOR    FROM SESION S
    JOIN USUARIO U ON S.ID_USUARIO=U.ID_USUARIO
    JOIN USUARIO_EMPRESA UE ON U.ID_USUARIO=UE.ID_USUARIO
    JOIN ADMINISTRADOR A ON UE.ID_USUARIO_EMPRESA=A.ID_USUARIO_EMPRESA
    JOIN EMPRESA E ON UE.ID_EMPRESA=E.ID_EMPRESA
    WHERE S.ID_SESION=:ID_SESION AND UE.ID_EMPRESA=:ID_EMPRESA
    AND E.ACTIVO='S' AND A.ACTIVO='S' AND UE.ACTIVO='S' AND U.ACTIVO='S'
    INTO :ID_ADMINISTRADOR; 
        
    IF (ID_ADMINISTRADOR IS NULL) THEN EXCEPTION EX_ADMINISTRADOR_ERROR;
    
    
    /*ACTUALIZAR LA SESION*/
    UPDATE SESION 
    SET FECHA_ACCESO='NOW'
    WHERE ID_SESION=:ID_SESION;
    /*VOLVER*/
    OK='S';
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE PRI_SESION_TRABAJADOR(ID_SESION T_ID,ID_EMPRESA T_ID)
RETURNS(OK T_LOGICO)
AS
DECLARE ID_TRABAJADOR T_ID;
BEGIN 
    SELECT T.ID_TRABAJADOR FROM SESION S
    JOIN USUARIO U ON S.ID_USUARIO=U.ID_USUARIO
    JOIN USUARIO_EMPRESA UE ON U.ID_USUARIO=UE.ID_USUARIO
    JOIN TRABAJADOR  T ON UE.ID_USUARIO_EMPRESA=T.ID_USUARIO_EMPRESA
    JOIN EMPRESA E ON UE.ID_EMPRESA=E.ID_EMPRESA
    WHERE S.ID_SESION=:ID_SESION AND UE.ID_EMPRESA=:ID_EMPRESA
    AND E.ACTIVO='S' AND T.ACTIVO='S' AND UE.ACTIVO='S' AND U.ACTIVO='S'
    INTO :ID_TRABAJADOR; 
        
    IF (ID_TRABAJADOR IS NULL) THEN EXCEPTION EX_TRABAJADOR_ERROR;
    
    /*ACTUALIZAR LA SESION*/
    UPDATE SESION 
    SET FECHA_ACCESO='NOW'
    WHERE ID_SESION=:ID_SESION;
    /*VOLVER*/
    OK='S';
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE PRI_SESION_ROLES(ID_SESION T_ID,ID_EMPRESA T_ID, ROL T_ROL )
RETURNS(OK T_LOGICO)
AS
BEGIN
  IF ((ROL<>'ROL_SUPER_ADMIN') AND (ROL<>'ROL_ADMIN') AND (ROL<>'ROL_TRABAJADOR')) 
  THEN EXCEPTION EX_ROL_ERROR;
  IF(ROL='ROL_SUPER_ADMIN') THEN SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK;
  IF(ROL='ROL_ADMIN') THEN SELECT OK FROM PRI_SESION_ADMIN(:ID_SESION,:ID_EMPRESA) INTO :OK;
  IF(ROL='ROL_TRABAJADOR') THEN SELECT OK FROM PRI_SESION_TRABAJADOR(:ID_SESION,:ID_EMPRESA) INTO :OK;
   
  SUSPEND;
END^


/* CRUD USUARIO */
CREATE OR ALTER PROCEDURE PUB_USUARIO_I(
    ID_USUARIO T_ID,
    NOMBRE T_NOMBRE_USUARIO,
    APELLIDOS T_APELLIDOS,
    MAIL T_MAIL,
    CLAVE T_CLAVE
)
RETURNS(
    OK T_LOGICO
)
AS
DECLARE MAIL_B T_MAIL;
BEGIN
    SELECT U.MAIL FROM USUARIO U  WHERE U.MAIL=:MAIL INTO :MAIL_B; 
    IF (MAIL_B IS NOT NULL) THEN EXCEPTION EX_USUARIO_MAIL_EXISTE;
 
    INSERT INTO USUARIO(ID_USUARIO,
    NOMBRE,APELLIDOS,MAIL,CLAVE, ACTIVO)
    VALUES (:ID_USUARIO,
    :NOMBRE,:APELLIDOS,:MAIL,:CLAVE, 'S');
    OK='S';
    SUSPEND;
END^

/* CRUD EMPRESA */
CREATE OR ALTER PROCEDURE PUB_USUARIO_S_LOGIN(
ID_SESION_N T_ID,
IP T_IP,
MAIL T_MAIL,
CLAVE T_CLAVE)
RETURNS (
OK T_LOGICO,
ID_SESION T_ID,
ID_USUARIO T_ID,
SUPER_ADMIN T_LOGICO
)
AS
 DECLARE ID_SUPER_ADMIN T_ID;
BEGIN 
   SELECT U.ID_USUARIO, S.ID_SUPER_ADMIN FROM USUARIO U 
   LEFT JOIN SUPER_ADMIN S ON U.ID_USUARIO=S.ID_USUARIO
   WHERE U.MAIL=:MAIL AND U.CLAVE=:CLAVE AND U.ACTIVO ='S' 
   INTO :ID_USUARIO, :ID_SUPER_ADMIN;
   
   IF (ID_USUARIO IS NULL) THEN EXCEPTION EX_USUARIO_LOGIN_ERROR;
   
   IF (ID_SUPER_ADMIN IS NULL) 
   THEN SUPER_ADMIN='N';
   ELSE SUPER_ADMIN='S';
   
   /* CREAR SESION*/
   INSERT INTO SESION(ID_SESION,ID_USUARIO,FECHA_INICIO,
   FECHA_ACCESO,FECHA_FIN,IP)
   VALUES(:ID_SESION_N,:ID_USUARIO,'NOW','NOW',NULL,:IP);
   ID_SESION=ID_SESION_N;     
   OK='S';
   
   
   SUSPEND;
END^



CREATE OR ALTER PROCEDURE PUB_EMPRESA_S(ID_SESION T_ID,ACTIVO_B T_LOGICO)
RETURNS(
ID_EMPRESA T_ID,
NOMBRE T_NOMBRE_EMPRESA,
ACTIVO T_LOGICO
) 
AS
DECLARE OK T_LOGICO;
BEGIN 
SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK;
FOR
    SELECT E.ID_EMPRESA,E.NOMBRE,E.ACTIVO 
    FROM EMPRESA E
    WHERE E.ACTIVO=:ACTIVO_B
    INTO :ID_EMPRESA,:NOMBRE,:ACTIVO
DO SUSPEND;
END^

CREATE OR ALTER PROCEDURE PUB_EMPRESA_S_ID(ID_SESION T_ID,ID_EMPRESA_B T_ID)
RETURNS(
ID_EMPRESA T_ID,
NOMBRE T_NOMBRE_EMPRESA,
ACTIVO T_LOGICO
) 
AS
DECLARE OK T_LOGICO;
BEGIN 
SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK;

SELECT E.ID_EMPRESA,E.NOMBRE,E.ACTIVO 
FROM EMPRESA E
WHERE E.ID_EMPRESA=:ID_EMPRESA_B
INTO :ID_EMPRESA,:NOMBRE,:ACTIVO;
SUSPEND;
END^


CREATE OR ALTER PROCEDURE PUB_EMPRESA_I(ID_SESION T_ID, ID_EMPRESA T_ID,
NOMBRE T_NOMBRE_EMPRESA)
RETURNS (OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK; 
    INSERT INTO EMPRESA(ID_EMPRESA,NOMBRE,ACTIVO)
    VALUES(:ID_EMPRESA, :NOMBRE, 'S');
    SUSPEND; 
END^

CREATE OR ALTER PROCEDURE PUB_EMPRESA_D(ID_SESION T_ID,ID_EMPRESA T_ID)
RETURNS (OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK; 
    DELETE FROM EMPRESA WHERE ID_EMPRESA=:ID_EMPRESA;
    SUSPEND; 
END^

CREATE OR ALTER PROCEDURE PUB_EMPRESA_U_NOMBRE(ID_SESION T_ID, ID_EMPRESA T_ID, 
NOMBRE T_NOMBRE_EMPRESA)
RETURNS (OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK; 
    UPDATE EMPRESA SET
    NOMBRE = :NOMBRE
    WHERE ID_EMPRESA=:ID_EMPRESA;
    SUSPEND; 
END^

CREATE OR ALTER PROCEDURE PUB_EMPRESA_U_ACTIVO(ID_SESION T_ID, ID_EMPRESA T_ID, 
ACTIVO T_LOGICO)
RETURNS (OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK; 
    UPDATE EMPRESA SET
    ACTIVO = :ACTIVO
    WHERE ID_EMPRESA=:ID_EMPRESA;
    OK='S';
    SUSPEND; 
END^



CREATE OR ALTER PROCEDURE PUB_USUARIO_EMPRESA_S(ID_SESION T_ID,ID_EMPRESA_B T_ID, ROL T_ROL,
PATRON T_APELLIDOS, ACTIVO_B T_LOGICO)
RETURNS(
ID_USUARIO_EMPRESA T_ID,
ID_EMPRESA T_ID,
ID_USUARIO T_ID,
NOMBRE T_NOMBRE_USUARIO,
APELLIDOS T_APELLIDOS,
NIF T_NIF,
ACTIVO T_LOGICO,
DIR T_DIR
)
AS
DECLARE OK T_LOGICO;
BEGIN

SELECT OK FROM PRI_SESION_ROLES(:ID_SESION,:ID_EMPRESA_B, :ROL) INTO :OK;

FOR 
  SELECT  ID_USUARIO_EMPRESA, ID_EMPRESA, ID_USUARIO, NOMBRE,
  APELLIDOS, NIF, ACTIVO, DIR 
  FROM USUARIO_EMPRESA UE
  WHERE UE.ID_EMPRESA = :ID_EMPRESA_B AND
  UE.ACTIVO = :ACTIVO_B AND 
  UE.APELLIDOS CONTAINING :PATRON
  INTO :ID_USUARIO_EMPRESA, :ID_EMPRESA, :ID_USUARIO, :NOMBRE,
  :APELLIDOS, :NIF, :ACTIVO, :DIR 
DO SUSPEND;
END^


CREATE OR ALTER PROCEDURE PUB_USUARIO_EMPRESA_S_ID(ID_SESION T_ID, ROL T_ROL,
ID_USUARIO_EMPRESA_B T_ID)
RETURNS(
ID_USUARIO_EMPRESA T_ID,
ID_EMPRESA T_ID,
ID_USUARIO T_ID,
NOMBRE T_NOMBRE_USUARIO,
APELLIDOS T_APELLIDOS,
NIF T_NIF,
ACTIVO T_LOGICO,
DIR T_DIR
)
AS
DECLARE ID_EMPRESA_B T_ID;
DECLARE OK T_LOGICO;
BEGIN
    
    SELECT  UE.ID_EMPRESA  FROM USUARIO_EMPRESA UE 
    WHERE UE.ID_USUARIO_EMPRESA= :ID_USUARIO_EMPRESA INTO :ID_EMPRESA;
    SELECT OK FROM PRI_SESION_ROLES(:ID_SESION,:ID_EMPRESA_B, :ROL) INTO :OK;

  SELECT  ID_USUARIO_EMPRESA, ID_EMPRESA, ID_USUARIO, NOMBRE,
  APELLIDOS, NIF, ACTIVO, DIR 
  FROM USUARIO_EMPRESA UE
  WHERE UE.ID_USUARIO_EMPRESA = :ID_USUARIO_EMPRESA_B
  INTO :ID_USUARIO_EMPRESA, :ID_EMPRESA, :ID_USUARIO, :NOMBRE,
  :APELLIDOS, :NIF, :ACTIVO, :DIR; 
  SUSPEND;
END^


	

CREATE OR ALTER PROCEDURE PUB_USUARIO_EMPRESA_I(
ID_SESION T_ID, ROL T_ROL,
ID_USUARIO_EMPRESA T_ID,
ID_EMPRESA T_ID,
MAIL T_MAIL,
NOMBRE T_NOMBRE_USUARIO,
APELLIDOS T_APELLIDOS,
NIF T_NIF,
DIR T_DIR
) 
RETURNS (
OK T_LOGICO)

AS 
DECLARE ID_USUARIO T_ID;
BEGIN 


    SELECT OK FROM PRI_SESION_ROLES(:ID_SESION,:ID_EMPRESA, :ROL) INTO :OK;
    
    SELECT ID_USUARIO FROM USUARIO U 
    WHERE U.MAIL = :MAIL INTO :ID_USUARIO;
    IF (ID_USUARIO IS NULL) THEN EXCEPTION EX_USUARIO_MAIL_NO_EXISTE;
    
    INSERT INTO USUARIO_EMPRESA (ID_USUARIO_EMPRESA, ID_EMPRESA, ID_USUARIO, NOMBRE,
    APELLIDOS, NIF, ACTIVO, DIR)
    VALUES (
    :ID_USUARIO_EMPRESA, :ID_EMPRESA, :ID_USUARIO, :NOMBRE,
    :APELLIDOS, :NIF, 'S', :DIR
    );
    OK='S';
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE PUB_USUARIO_EMPRESA_U(
ID_SESION T_ID, ROL T_ROL,
ID_USUARIO_EMPRESA T_ID,
NOMBRE T_NOMBRE_USUARIO,
APELLIDOS T_APELLIDOS,
NIF T_NIF,
DIR T_DIR
) 
RETURNS (
OK T_LOGICO)

AS
DECLARE ID_EMPRESA T_ID; 
BEGIN
    SELECT  UE.ID_EMPRESA  FROM USUARIO_EMPRESA UE 
    WHERE UE.ID_USUARIO_EMPRESA= :ID_USUARIO_EMPRESA INTO :ID_EMPRESA;
  SELECT OK FROM PRI_SESION_ROLES(:ID_SESION,:ID_EMPRESA, :ROL) INTO :OK;
 
  UPDATE USUARIO_EMPRESA UE
  SET 
    NOMBRE=:NOMBRE,
    APELLIDOS=:APELLIDOS,
    NIF=:NIF,
    DIR=:DIR
    WHERE UE.ID_USUARIO_EMPRESA=:ID_USUARIO_EMPRESA;
  OK='S';
  SUSPEND;
    
END^

CREATE OR ALTER PROCEDURE PUB_USUARIO_EMPRESA_U_ACTIVO(
ID_SESION T_ID, ROL T_ROL,
ID_USUARIO_EMPRESA T_ID,
ACTIVO T_LOGICO
) 
RETURNS (
OK T_LOGICO)

AS 
DECLARE ID_EMPRESA T_ID; 
BEGIN
   SELECT  UE.ID_EMPRESA  FROM USUARIO_EMPRESA UE 
    WHERE UE.ID_USUARIO_EMPRESA= :ID_USUARIO_EMPRESA INTO :ID_EMPRESA;
  SELECT OK FROM PRI_SESION_ROLES(:ID_SESION,:ID_EMPRESA, :ROL) INTO :OK; 
  
  UPDATE USUARIO_EMPRESA UE
  SET 
    ACTIVO=:ACTIVO
    WHERE UE.ID_USUARIO_EMPRESA=:ID_USUARIO_EMPRESA;
  OK='S';
  SUSPEND;
END^  
  
CREATE OR ALTER PROCEDURE PUB_USUARIO_EMPRESA_D(
ID_SESION T_ID, ROL T_ROL,
ID_USUARIO_EMPRESA T_ID)
RETURNS (
OK T_LOGICO)
AS
DECLARE ID_EMPRESA T_ID;  
BEGIN
 SELECT  UE.ID_EMPRESA  FROM USUARIO_EMPRESA UE 
    WHERE UE.ID_USUARIO_EMPRESA= :ID_USUARIO_EMPRESA INTO :ID_EMPRESA;
  SELECT OK FROM PRI_SESION_ROLES(:ID_SESION,:ID_EMPRESA, :ROL) INTO :OK;   
   DELETE FROM USUARIO_EMPRESA UE 
   WHERE UE.ID_USUARIO_EMPRESA=:ID_USUARIO_EMPRESA;
   OK='S';
  SUSPEND;    
    
END^

CREATE OR ALTER PROCEDURE PUB_ADMINISTRADOR_S(ID_SESION T_ID,
ID_EMPRESA T_ID, ACTIVO_B T_LOGICO)
RETURNS (
ID_ADMINISTRADOR T_ID,
ID_USUARIO_EMPRESA T_ID,
ACTIVO T_LOGICO,
NOMBRE T_NOMBRE_USUARIO,
APELLIDOS T_APELLIDOS,
NIF T_NIF,
DIR T_DIR)
AS
DECLARE OK T_LOGICO;
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK;
FOR
    SELECT A.ID_ADMINISTRADOR,A.ID_USUARIO_EMPRESA,A.ACTIVO,UE.NOMBRE,UE.APELLIDOS,UE.NIF,UE.DIR                          
    FROM ADMINISTRADOR A
    JOIN USUARIO_EMPRESA UE ON UE.ID_USUARIO_EMPRESA = A.ID_USUARIO_EMPRESA
    WHERE UE.ID_EMPRESA =:ID_EMPRESA AND A.ACTIVO =:ACTIVO_B
    INTO :ID_ADMINISTRADOR,:ID_USUARIO_EMPRESA,:ACTIVO,:NOMBRE,:APELLIDOS,:NIF,:DIR
    
DO SUSPEND;
END^

CREATE OR ALTER PROCEDURE PUB_ADMINISTRADOR_I(ID_SESION T_ID,
ID_ADMINISTRADOR T_ID, 
ID_USUARIO_EMPRESA T_ID
)
RETURNS (
OK T_LOGICO
)
AS
BEGIN
     SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK;
     
   INSERT INTO ADMINISTRADOR(ID_ADMINISTRADOR, ID_USUARIO_EMPRESA, ACTIVO)
   VALUES(:ID_ADMINISTRADOR, :ID_USUARIO_EMPRESA,'S');
SUSPEND;
END^


CREATE OR ALTER PROCEDURE PUB_ADMINISTRADOR_U_ACTIVO(ID_SESION T_ID,ID_ADMINISTRADOR T_ID, 
ACTIVO T_LOGICO)
RETURNS(
OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK;
    
    UPDATE ADMINISTRADOR
    SET ACTIVO =:ACTIVO
    WHERE ID_ADMINISTRADOR =:ID_ADMINISTRADOR;
SUSPEND;
    
END^

CREATE OR ALTER PROCEDURE PUB_ADMINISTRADOR_D(ID_ADMINISTRADOR T_ID)
RETURNS (OK T_LOGICO)
AS
BEGIN
    DELETE FROM ADMINISTRADOR
    WHERE ID_ADMINISTRADOR =:ID_ADMINISTRADOR;
SUSPEND;
END^





SET TERM;^