CREATE OR ALTER EXCEPTION EX_USUARIO_MAIL_EXISTE '';
CREATE OR ALTER EXCEPTION EX_USUARIO_LOGIN_ERROR '';
CREATE OR ALTER EXCEPTION EX_SUPER_ADMIN_ERROR '';

SET TERM ^;

CREATE OR ALTER PROCEDURE PRI_SESION_SUPER_ADMIN(ID_SESION T_ID)
RETURNS(OK T_LOGICO)
AS
DECLARE ID_SUPER_ADMIN T_ID;
BEGIN 
    /*COMPROBAR SI ES SUPER_ADMIN*/
    SELECT A.ID_SUPER_ADMIN 
    FROM SUPER_ADMIN A
    JOIN USUARIO U ON A.ID_USUARIO=U.ID_USUARIO
    JOIN SESION S ON U.ID_USUARIO=S.ID_USUARIO
    WHERE S.ID_SESION=:ID_SESION
    AND U.ACTIVO='S'
    AND S.FECHA_FIN IS NULL
    INTO :ID_SUPER_ADMIN;
    IF (ID_SUPER_ADMIN IS NULL) THEN EXCEPTION EX_SUPER_ADMIN_ERROR;
    /*ACTUALIZAR LA SESION*/
    UPDATE SESION 
    SET FECHA_ACCESO='NOW'
    WHERE ID_SESION=:ID_SESION;
    /*VOLVER*/
    OK='S';
    SUSPEND;
END^



/* CRUD USUARIO */
CREATE OR ALTER PROCEDURE PUB_USUARIO_I(
    ID_USUARIO T_ID,
    NOMBRE T_NOMBRE_USUARIO,
    APELLIDOS T_APELLIDOS,
    MAIL T_MAIL,
    CLAVE T_CLAVE
)
RETURNS(
    OK T_LOGICO
)
AS
DECLARE MAIL_B T_MAIL;
BEGIN
    SELECT U.MAIL FROM USUARIO U  WHERE U.MAIL=:MAIL INTO :MAIL_B; 
    IF (MAIL_B IS NOT NULL) THEN EXCEPTION EX_USUARIO_MAIL_EXISTE;
 
    INSERT INTO USUARIO(ID_USUARIO,
    NOMBRE,APELLIDOS,MAIL,CLAVE, ACTIVO)
    VALUES (:ID_USUARIO,
    :NOMBRE,:APELLIDOS,:MAIL,:CLAVE, 'S');
    OK='S';
    SUSPEND;
END^

/* CRUD EMPRESA */
CREATE OR ALTER PROCEDURE PUB_USUARIO_S_LOGIN(
ID_SESION_N T_ID,
IP T_IP,
MAIL T_MAIL,
CLAVE T_CLAVE)
RETURNS (
OK T_LOGICO,
ID_SESION T_ID,
ID_USUARIO T_ID
)
AS

BEGIN 
   SELECT U.ID_USUARIO FROM USUARIO U 
   WHERE U.MAIL=:MAIL AND U.CLAVE=:CLAVE AND U.ACTIVO ='S' INTO :ID_USUARIO;
   IF (ID_USUARIO IS NULL) THEN EXCEPTION EX_USUARIO_LOGIN_ERROR;

   /* CREAR SESION*/
   INSERT INTO SESION(ID_SESION,ID_USUARIO,FECHA_INICIO,
   FECHA_ACCESO,FECHA_FIN,IP)
   VALUES(:ID_SESION_N,:ID_USUARIO,'NOW','NOW',NULL,:IP);
   ID_SESION=ID_SESION_N;     
   OK='S';
   SUSPEND;
END^



CREATE OR ALTER PROCEDURE PUB_EMPRESA_S(ID_SESION T_ID,ACTIVO_B T_LOGICO)
RETURNS(
ID_EMPRESA T_ID,
NOMBRE T_NOMBRE_EMPRESA,
ACTIVO T_LOGICO
) 
AS
DECLARE OK T_LOGICO;
BEGIN 
SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK;
FOR
    SELECT E.ID_EMPRESA,E.NOMBRE,E.ACTIVO 
    FROM EMPRESA E
    WHERE E.ACTIVO=:ACTIVO_B
    INTO :ID_EMPRESA,:NOMBRE,:ACTIVO
DO SUSPEND;
END^

CREATE OR ALTER PROCEDURE PUB_EMPRESA_S_ID(ID_SESION T_ID,ID_EMPRESA_B T_ID)
RETURNS(
ID_EMPRESA T_ID,
NOMBRE T_NOMBRE_EMPRESA,
ACTIVO T_LOGICO
) 
AS
DECLARE OK T_LOGICO;
BEGIN 
SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK;

SELECT E.ID_EMPRESA,E.NOMBRE,E.ACTIVO 
FROM EMPRESA E
WHERE E.ID_EMPRESA=:ID_EMPRESA_B
INTO :ID_EMPRESA,:NOMBRE,:ACTIVO;
SUSPEND;
END^


CREATE OR ALTER PROCEDURE PUB_EMPRESA_I(ID_SESION T_ID, ID_EMPRESA T_ID,
NOMBRE T_NOMBRE_EMPRESA)
RETURNS (OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK; 
    INSERT INTO EMPRESA(ID_EMPRESA,NOMBRE,ACTIVO)
    VALUES(:ID_EMPRESA, :NOMBRE, 'S');
    SUSPEND; 
END^

CREATE OR ALTER PROCEDURE PUB_EMPRESA_D(ID_SESION T_ID,ID_EMPRESA T_ID)
RETURNS (OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK; 
    DELETE FROM EMPRESA WHERE ID_EMPRESA=:ID_EMPRESA;
    SUSPEND; 
END^

CREATE OR ALTER PROCEDURE PUB_EMPRESA_U_NOMBRE(ID_SESION T_ID, ID_EMPRESA T_ID, 
NOMBRE T_NOMBRE_EMPRESA)
RETURNS (OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK; 
    UPDATE EMPRESA SET
    NOMBRE = :NOMBRE
    WHERE ID_EMPRESA=:ID_EMPRESA;
    SUSPEND; 
END^

CREATE OR ALTER PROCEDURE PUB_EMPRESA_U_ACTIVO(ID_SESION T_ID, ID_EMPRESA T_ID, 
ACTIVO T_LOGICO)
RETURNS (OK T_LOGICO)
AS
BEGIN
    SELECT OK FROM PRI_SESION_SUPER_ADMIN(:ID_SESION) INTO :OK; 
    UPDATE EMPRESA SET
    ACTIVO = :ACTIVO
    WHERE ID_EMPRESA=:ID_EMPRESA;
    OK='S';
    SUSPEND; 
END^





SET TERM;^