INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDOS, MAIL, CLAVE, ACTIVO) VALUES ('LOTJYdiQ', 'Alfonso', 'Pereira', 'alfonsopereira@gmail.com', '551db2b0cd87b44cf3702690805545de', 'S');
INSERT INTO SUPER_ADMIN (ID_SUPER_ADMIN, ID_USUARIO) VALUES ('SA1', 'LOTJYdiQ');
INSERT INTO EMPRESA (ID_EMPRESA, NOMBRE, ACTIVO) VALUES ('Wb8S8rNP', 'Altia', 'S');
