INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDOS, MAIL, CLAVE, ACTIVO) 
VALUES ('WRGpnhSx', 'Alfonso', 'Pereira', 'alfonsopereira@gmail.com', '551db2b0cd87b44cf3702690805545de', 'S');

INSERT INTO SUPER_ADMIN (ID_SUPER_ADMIN, ID_USUARIO) 
VALUES ('admin1', 'WRGpnhSx');

