INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDOS, MAIL, CLAVE, ACTIVO) VALUES ('UjQaNnuw', 'Maria', 'Gutierrez', 'maria@gmail.com', '62e3d9237a61febb5a7200314032f4de', 'S');
INSERT INTO SUPER_ADMIN (ID_SUPER_ADMIN, ID_USUARIO) VALUES ('admin1', 'UjQaNnuw');
